### ISSUE TITLE
Crate issue on target mipsel

### ISSUE THREAD

**Issue by ddemarco5** [dcuddeback/serial-rs#47] opened 2017-07-01 03:46 UTC
Compiling this crate for target "mipsel-unknown-linux-musl" yields a problem I've never seen before...

`error[E0463]: can't find crate for `termios`
 --> /home//CARGO_HOME/git/checkouts/serial-rs-2342861c2cbe3710/9025963/src/posix/tty.rs:2:1
  |
2 | extern crate termios;
  | ^^^^^^^^^^^^^^^^^^^^^ can't find crate`

It looks like you're missing a line for the target in your Cargo.toml
"mipsel-unknown-linux-musl" might be a good idea to add.

**Comment by dcuddeback** [comment] 2017-07-01 19:13
I have an old branch that updates `Cargo.toml` to use the `cfg()` syntax, which was introduced to Cargo well after this library was written. If the issue is a missing target in `Cargo.toml`, that should fix it. Thanks for reminding me about this issue. I'll see what I can do about releasing that this weekend.

**Comment by dcuddeback** [comment] 2017-07-02 01:29
@ddemarco5 Could you try the version that I just published (0.4.0)?

**Comment by dcuddeback** [comment] 2017-07-30 22:16
This should be fixed in the v0.4.0 release. Please feel free to file a new bug if v0.4.0 doesn't resolve this.

**Closed as completed by dcuddeback** 2017-07-30 22:16 UTC
